runtime: python37
env: flex
entrypoint: flask run

runtime_config:
  python_version: 3

env_variables:
  FLASK_APP: "capstone2020.app"
  
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
